# 
# YAML init file for Pulse SMS listener
#

globals:
  bind_host:                   0.0.0.0
  port:                        9050
  debug:                       True
  logfile:                     pulsesvc.log
  project_directory:           $PULSE_HOME
  service_module:              pulse_sms_services
  transform_function_module:   pulse_transforms
  decoder_module:              pulse_decode            


service_objects:

  sms:
    class: SMSService
    init_params:
      - name: account_sid
        value: $TWILIO_ACCT_SID

      - name: auth_token
        value: $TWILIO_AUTH_TOKEN

      - name: source_mobile_number
        value: "9178102234"

data_shapes:
  default:
    fields:

  system_status_shape:
    fields:
     
transforms:
  ping:
    route:              /ping
    method:             GET
    input_shape:        default
    output_mimetype:    application/json

  system_status:
    route:              /status
    method:             GET
    input_shape:        system_status_shape
    output_mimetype:    application/json

  sms_responder:
    route:              /sms
    method:             POST
    input_shape:        default
    output_mimetype:    text/json

 

decoders:
  application/json; charset=utf-8: decode_json


error_handlers:
        - error:                NoSuchObjectException
          tx_status_code:       HTTP_NOT_FOUND 
                
        - error:                DuplicateIDException
          tx_status_code:       HTTP_BAD_REQUEST