# 
# YAML init file for Pulse Atrium server
#

globals:  
  debug:                       True
  logfile:                     pulsesvc.log
  project_directory:           $PULSE_HOME
  service_module:              atrium_services
  message_handler_module:      atrium_handlers

service_objects:


settings:
  rcv_channel_id: 'atriumd_ipc_rcv_channel'
  send_channel_id: 'atriumd_ipc_send_channel'
  redis_host: 172.25.0.2
  redis_port: 6379
  redis_db: 0
  

message_types:
  unknown:
    handler_class: UnknownMessageHandler
    handler_poolsize: 1

  test:
    handler_class: TestMessageHandler
    handler_poolsize: 1

  
    