version: '3'

networks:
  atrium-net:
    driver: bridge

services:
  
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - default
      - atrium-net

  db:
    build:
      dockerfile: pgsql.Dockerfile
      context: .
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"
    networks:
      - default
    volumes:
      - ./pulsedb/init:/docker-entrypoint-initdb.d
 

volumes:
  pgdata1:
    driver: local
